name: Build Pre-release

on:
  release:
    types: [prereleased]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Build & Push the Docker image
      - name: Build & Push
        run: |
          echo tag ${GITHUB_REF_NAME}
      - name: Notify changelog
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://chglg.fly.dev/v1/changelog'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.CHANGELOG_API_KEY }}"}'
          timeout: 30000
          escapeData: 'true'
          data: >-
            {   
              "app_name": "Telegram", 
              "icon_url": "https://cdn.discordapp.com/emojis/1097390168723435550.webp?size=96&quality=lossless", 
              "repo": "https://github.com/${{ github.repository }}", 
              "tag": "${{ github.ref }}"
            }