name: Build and Deploy to GKE Dev

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "My fancy build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v1
      - name: Create Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version v$RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
