name: Release

on:
  push:
    branches:
      - develop
    tags:
      - "v*"

jobs:
  build:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: gen_changelog
        run: |
          docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog --output RELEASE.md v0.0.5
          ls
        # uses: bdashrad/git-chglog-action@v2.0.3
        # with:
          # tag: ${{ github.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md
          draft: true
          token: ${{ secrets.GH_PAT }}
        env:
          GITHUB_REPOSITORY: lmquang/release
